# Site
name: "Mohamed Ali JAMAOUI"
title: "Mohamed Ali JAMAOUI"
description: "Machine Learning, Deep Learning, Data Science & More"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-21227488-2'
disqus: ''
# mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  mohamed-ali:
    name: Mohamed Ali JAMAOUI
    display_name: Mohamed Ali
    avatar: 'assets/images/dali.png'
    email: myblog@gmail.com
    web: https://github.com/mohamed-ali
    twitter: https://twitter.com/JamaouiMohamedA
    description: "A machine learning engineer, enthusiast about data science, machine learning, Deep learning, software engineering and mostly, making the world a better place :)"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

# Enable rendering latex style mathematics
mathjax: true

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
